import type { Metadata } from "next";
import Providers from "./providers";
import { notFound } from "next/navigation";
import "./globals.css";
import { geistSans, geistMono } from "../fonts";
import fs from "fs/promises";
import path from "path";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Load messages
  let messages: Record<string, any> = {};
  try {
    const messagesDir = path.join(process.cwd(), "messages", locale);
    const entries = await fs.readdir(messagesDir);
    for (const entry of entries) {
      if (entry.endsWith(".json")) {
        try {
          const content = await fs.readFile(
            path.join(messagesDir, entry),
            "utf8"
          );
          const parsed = JSON.parse(content);
          Object.assign(messages, parsed);
        } catch (e) {
          // skip invalid file
        }
      }
    }
    // if no messages were loaded, fallback to single-file load
    if (Object.keys(messages).length === 0) {
      // try legacy single file
      messages = (await import(`../../../messages/${locale}.json`)).default;
    }
  } catch (e) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers locale={locale} messages={messages}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
